#+TITLE: 3macS3c Doom Config
#+AUTHOR: 3macS3c
#+DESCRIPTION:
#+auto_tangle: t
#+STARTUP: showeverything

* TABLE OF CONTENTS :TOC:
:PROPERTIES:
:ID:       000a9879-f073-45f6-9018-8955d7976c03
:END:
- [[#literate-config][Literate Config:]]
- [[#doom-main-config][Doom Main Config:]]
  - [[#general-settings][General Settings:]]
  - [[#revert][Revert:]]
  - [[#org-mode][ORG MODE:]]
  - [[#markdown][Markdown:]]
  - [[#quality-of-life][Quality Of Life:]]
- [[#packagesel][packages.el:]]
- [[#initel][init.el]]

* Literate Config:
:PROPERTIES:
:ID:       8b109ffb-1a46-464f-b168-4d5efac2f955
:END:
* Doom Main Config:
:PROPERTIES:
:ID:       361a35c9-3eac-47ec-af51-ad90d4d8c2f1
:header-args: :tangle ~/Dropbox/40-49_Career/45-KaliShared/45.00-KaliConfigs/Doom/config.el
:END:


** General Settings:
:PROPERTIES:
:ID:       a17ee53a-a4ba-42cd-b41d-cabfff9a266f
:END:
*** User Information:
:PROPERTIES:
:ID:       a2bd54eb-f25d-446b-8c5a-a4fb3c2199a0
:END:
#+begin_src emacs-lisp
(setq user-full-name "3macS3c")
#+end_src

*** Set Theme and line Numbers:
:PROPERTIES:
:ID:       79e6107b-75f2-45cc-b02e-40095f35b917
:END:
#+begin_src emacs-lisp
;;Select my preffered theme:
(setq doom-theme 'doom-dracula)
;; This determines the style of line numbers in effect. If set to `nil', line
;; numbers are disabled. For relative line numbers, set this to `relative'.
(setq display-line-numbers-type t)
#+end_src
*** Beacon:
:PROPERTIES:
:ID:       29622efc-52c7-4b7a-beaa-edbb1363e065
:END:
Never lose your cursor.  When you scroll, your cursor will shine!  This is a global minor-mode. Turn it on everywhere with:

#+begin_src emacs-lisp
(beacon-mode 1)
#+end_src
*** Graphics: Pixel-precision scrolling:
:PROPERTIES:
:ID:       db383e18-c11a-4111-aa55-6aa95f21771d
:END:
#+begin_src emacs-lisp
(when (version< "29.0.50" emacs-version)
  (pixel-scroll-precision-mode))
#+end_src
** Revert:
:PROPERTIES:
:ID:       46b0191d-6a14-43e0-a459-b125dab67b7a
:END:
Doom Emacs uses 'SPC b' for keybindings related to bookmarks and buffers.

*** Global Auto Revert
:PROPERTIES:
:ID:       f2f913de-6630-41fa-98a6-161c56929db5
:END:
A buffer can get out of sync with respect to its visited file on disk if that file is changed by another program. To keep it up to date, you can enable Auto Revert mode by typing M-x auto-revert-mode, or you can set it to be turned on globally with 'global-auto-revert-mode'.  I have also turned on Global Auto Revert on non-file buffers, which is especially useful for 'dired' buffers.

#+begin_src emacs-lisp
;;Global Auto Revert
(global-auto-revert-mode 1)
(setq global-auto-revert-non-file-buffers t)
#+end_src

** ORG MODE:
:PROPERTIES:
:ID:       a9a32dc9-eaa0-4866-9cc0-5573061c5ec1
:END:
- This is where the vast majority of my customization lies. As I live mostly in ORG Mode.
*** ORG - Todo States:
:PROPERTIES:
:ID:       b5055bad-0e4b-46c8-b728-f32400488f6c
:END:
Custom TODO states & Tags
#+begin_src emacs-lisp
;; CUSTOM org TODO states
(after! org
(setq org-todo-keywords
      '((sequence "TODO(t)"
         "NEXT(n)"
         "PLANNING(p)"
         "IN-PROGRESS(i)"
         "WEEKLY-GOAL(m)"
         "GOAL(g)"
         "WAITING(w)"
         "WORK(b)"
         "HABIT(h)"
         "PROJECT(P)"
         "CALENDAR(c)"
         "NOTE(N)"
         "AREA(a)"
         "|"
         "DONE(d!)"
         "COMPLETE(C!)"
         "HOLD(h)"
         "SOMEDAY(s)"
         "RABBITHOLE!(R)")
        )))

;; CUSTOM TODO colors
(after! org
(setq org-todo-keyword-faces
      '(
        ("TODO" . (:foreground "#ffdd83" :weight bold))
        ("NEXT" . (:foreground "light coral" :weight bold))
        ("PLANNING" . (:foreground "#bd7091" :weight bold))
        ("IN-PROGRESS" . (:foreground "#ffb86c" :weight bold))
        ("WEEKLY-GOAL" . (:foreground "light sea green" :weight bold))
        ("GOAL" . (:foreground "LimeGreen" :weight bold))
        ("WAITING" . (:foreground "LightPink1" :weight bold))
        ("WORK" . (:foreground "Cyan" :weight bold))
        ("HABIT" . (:foreground "RoyalBlue3" :weight bold))
        ("PROJECT" . (:foreground "SlateBlue1" :weight bold))
        ("CALENDAR" . (:foreground "chocolate" :weight bold))
        ("NOTE" . (:foreground "#7d9dc0" :background "#ffb86c" :weight bold))
        ("AREA" . (:foreground "#7d9dc0" :weight bold))

        ("DONE" . (:foreground "white" :weight bold))
        ("COMPLETE" . (:strikethrough t :foreground "light gray" :weight bold))
        ("HOLD" . (:foreground "Grey46" :weight bold))
        ("SOMEDAY" . (:foreground "cyan1" :weight bold))
        )))

;; Custom Tag colors
(setq org-tag-faces
      '(
        ("planning"  . (:foreground "mediumPurple1" :weight bold))
        ("@research"   . (:foreground "royalblue1"    :weight bold))
        ("QA"        . (:foreground "sienna"        :weight bold))
        ("CRITICAL"  . (:foreground "red1"          :weight bold))
        ("HABIT"  . (:foreground "pink"          :weight bold))
        )
      )
#+end_src

*** ORG - CRYPT Setup:
:PROPERTIES:
:ID:       b0172336-1c78-43ba-9d4d-328ea1cb2bec
:END:

#+begin_src emacs-lisp
;;;;;;;;;;;;;;;;;;;;;ORG CRYPT
;; ORG CRYPT TAG Setup for inline encryption
;; If I place "crypt" tag in any entry it will encrypt it.
(require 'org-crypt)
(org-crypt-use-before-save-magic)
(setq org-tags-exclude-from-inheritance '("crypt"))
;; GPG key to use for encryption
;; Either the Key ID or set to nil to use symmetric encryption.
(setq org-crypt-key nil)
;; Set shortut to decrypt easier.
(map! :leader
      :desc "Org Decrypt Entry"
      "d e" #'org-decrypt-entry)
#+end_src

*** ORG - Center Screen Shortcut:
:PROPERTIES:
:ID:       c7ff47ea-c1e2-494b-93b8-c8a161e0d8e6
:END:
- Easily recenter the screen my hitting leader + s + c
#+begin_src emacs-lisp
(map! :leader
      :desc "recenter-top-bottom"
      "s c" #'recenter-top-bottom)
#+end_src

*** ORG - Preview Images in all files:
:PROPERTIES:
:ID:       e7a190f3-2341-449b-863e-ecbd8d5193d9
:END:
#+begin_src emacs-lisp
;; Preview images in all org files on launch
(setq org-startup-with-inline-images t)
;;Adjust images to an actual size that doesn't take up the entire screen.
(setq org-image-actual-width 600)

#+end_src

*** ORG - Auto Tangle:
:PROPERTIES:
:ID:       e68426f3-10d3-40ab-ace9-43aea005726f
:END:

- By adding this ~#+PROPERTY: header-args :tangle /Directory/name_of_file.extension~ to any org file I can output the code block contents to the specified location.

#+begin_src emacs-lisp

;; Enables auto tangling/exporting of code blocks to a unified code file form org mode.
(use-package! org-auto-tangle
  :defer t
  :hook (org-mode . org-auto-tangle-mode)
  :config
  (setq org-auto-tangle-default t))

#+end_src

*** ORG - Start all documents in overview mode:
:PROPERTIES:
:ID:       907ee898-45d6-49e4-90c4-c47299ee4ee0
:END:
- I have large org files with lots of nested headings, this makes it less cumbersome.
#+begin_src emacs-lisp
(setq org-startup-folded t)

#+end_src

*** ORG - Add ID to all ORG headindgs on save:
:PROPERTIES:
:ID:       e34a8157-fadf-462e-bdd5-b66eb4f4e790
:END:
- Add ID to all ORG headindgs on save:
  - I want the option to be able to import org roam if need be. This adds ID's to all headings so I can then easily back link.
#+begin_src emacs-lisp
(add-hook 'org-capture-prepare-finalize-hook 'org-id-get-create)
(defun my/org-add-ids-to-headlines-in-file ()
;  "Add ID properties to all headlines in the current file which
;do not already have one."
  (interactive)
  (org-map-entries 'org-id-get-create))
(add-hook 'org-mode-hook
          (lambda ()
            (add-hook 'before-save-hook 'my/org-add-ids-to-headlines-in-file nil 'local)))
#+end_src

*** ORG - Cosmetics:
:PROPERTIES:
:ID:       35aafda0-1f9c-4551-a4c8-79920bb74ac9
:END:
**** Cosmetics - Export with smart quotes:
:PROPERTIES:
:ID:       6cebe70b-2675-4d0f-b996-76e98c1eff69
:END:
- I use custom smart quotes so this helps me have them remain when exporting.
#+begin_src emacs-lisp
;; Export using my custom smart quotes.
(setq org-export-with-smart-quotes t)
#+end_src

**** Cosmetics - Hide Emphasis Markers:
:PROPERTIES:
:ID:       d50728fa-59ad-43fd-b305-3cd36934c7ea
:END:
- This means that the markers used for emphasis will no longer be visible and instead just the outcome.

#+begin_src emacs-lisp

;; Hide emphasis markers in text this means that MD and org syntax icons will not show
;; effectively acts as preview.

(after! org
(setq org-hide-emphasis-markers t))

#+end_src

**** Cosmetics - Colour Configuration:
:PROPERTIES:
:ID:       e3d89ffa-f86c-4810-917e-fc0e9dff2c78
:END:
#+begin_src emacs-lisp

;;Customize ORG higlighting
;; this controls the color of bold, italic, underline, verbatim, strikethrough

(after! org
(setq org-emphasis-alist
    ;; Purple Bold & Underline Brighter purple
  '(("*" (underline :weight black :foreground "#A061F9" ))
    ;; Red text highligted in yellow (important)
    ("/" (:weight black :background "#FF5555" :foreground "#F1FA8C" ))
    ;; Blue
    ("_" (:weight black :foreground "#79c6ff" ))
    ;;Higlighter  brighter yellow
    ("=" (underline :weight black :foreground "#F1FA8C" ))
    ;; Code block
    ("~" (:background "#6BB86B" :foreground "#575a71" ))
    ;; Red = Important red
    ("+" (underline bold :weight italic :foreground "#FF5555" )))))
    ;;("+" (bold :strike-through nil :foreground "#ffb86c" #cd5c5c )))))

#+end_src

**** Cosmetics - Headline Bullets and Folds:
:PROPERTIES:
:ID:       c6d4de16-3f32-4289-8afe-938621ca352f
:END:
#+begin_src emacs-lisp
(setq org-superstar-headline-bullets-list '("› "))
#+end_src
**** Cosmetics - Item Bullets:
:PROPERTIES:
:ID:       a1bb5e48-0a40-4830-9606-5d6579e79fe1
:END:
- Custom bulleted list
#+begin_src emacs-lisp

(setq org-superstar-item-bullet-alist '((?* . ?⋆)
                                        (?+ . ?‣)
                                        (?- . ?•)))
#+end_src
**** Cosmetics - Dropdown Icon:
:PROPERTIES:
:ID:       470a4470-638e-4988-ab34-43f2edce07bc
:END:
- Custom drop down icon.
#+begin_src emacs-lisp
(setq org-ellipsis " ⯯")
#+end_src

**** Cosmetics - Ligatures:
:PROPERTIES:
:ID:       c9f408ee-4427-48b2-b4e1-db259334f4ec
:END:
- Stolen from https://github.com/elken/doom
#+begin_src emacs-lisp
(setq-hook! org-mode
  prettify-symbols-alist '(("#+end_quote" . "”")
                           ("#+END_QUOTE" . "”")
                           ("#+begin_quote" . "“")
                           ("#+BEGIN_QUOTE" . "“")
                           ("#+end_src" . "«")
                           ("#+END_SRC" . "«")
                           ("#+begin_src" . "»")
                           ("#+BEGIN_SRC" . "»")
                           ("#+name:" . "»")
                           ("#+NAME:" . "»")))
#+end_src

**** Cosmetics - Indent Content under Headings:
:PROPERTIES:
:ID:       3a84bc56-571b-4ccc-b51d-5f6cbed31482
:END:
#+begin_src emacs-lisp
(setq org-adapt-indentation t)
#+end_src
**** Cosmetics - Indent All Org Files:
:PROPERTIES:
:ID:       4b6de76f-de9b-408e-9883-7819f89e9014
:END:
#+begin_src emacs-lisp
(require 'org-indent)
(setq org-startup-indented t)
#+end_src

** Markdown:
:PROPERTIES:
:ID:       f31b8cdf-d035-46c2-a125-d2385c013ea9
:END:
- Why have MD customization when I have org. Sometimes when writing reports this is the best option as it's compatible accross the board and doesn't require exporting, which with my custom org markers can be cumbersome.
*** Markdown: Line Numbers Display:
:PROPERTIES:
:ID:       bfffa396-eb29-4d4c-8a83-6ca9cb0576fd
:END:
#+begin_src emacs-lisp
;; Markdown & line settings
(setq display-line-numbers-type t)
(map! :leader
      :desc "Comment or uncomment lines" "TAB TAB" #'comment-line
      (:prefix ("t" . "toggle")
       :desc "Toggle line numbers" "l" #'doom/toggle-line-numbers
       :desc "Toggle line highlight in frame" "h" #'hl-line-mode
       :desc "Toggle line highlight globally" "H" #'global-hl-line-mode
       :desc "Toggle truncate lines" "t" #'toggle-truncate-lines))
#+end_src
*** Markdown: Set Custom Headers:
:PROPERTIES:
:ID:       1de325a2-07bd-4a41-860b-5394cc7c1ead
:END:

#+begin_src emacs-lisp
;Markdown: Set Custom Headers:
(custom-set-faces!
 ;; Headers
'(markdown-header-delimiter-face :foreground "#616161" :height 0.9)
'(markdown-header-face-1 :height 1.8 :foreground "#FF79C6" :weight extra-bold :inherit markdown-header-face)
'(markdown-header-face-2 :height 1.4 :foreground "#BD93F9" :weight extra-bold :inherit markdown-header-face)
'(markdown-header-face-3 :height 1.2 :foreground "#D4B8FB" :weight extra-bold :inherit markdown-header-face)
'(markdown-header-face-4 :height 1.15 :foreground "#FFA7D9" :weight bold :inherit markdown-header-face)
'(markdown-header-face-5 :height 1.1 :foreground "#E4D3FC" :weight bold :inherit markdown-header-face)
'(markdown-header-face-6 :height 1.05 :foreground "#5e81ac" :weight semi-bold :inherit markdown-header-face)

;;; Custom bold etc
'(markdown-code-face :background "#6BB86B" :foreground "#575a71")
'(markdown-line-break-face :weight extra-black :foreground "#79c6ff")
'(markdown-italic-face :weight black :foreground "#79c6ff")
'(markdown-list-face :weight black :foreground "#BD93F9")
'(markdown-bold-face :weight black :foreground "#A061F9"))
#+end_src

*** Markdown: Functions To Allow Markdown preview whilst typing:
:PROPERTIES:
:ID:       c8d0db5b-d4fa-45dd-a7e2-9d19058c556d
:END:
#+begin_src emacs-lisp
;; Enables markdown preview whilst creating doc.
 (defvar nb/current-line '(0 . 0)
   "(start . end) of current line in current buffer")
 (make-variable-buffer-local 'nb/current-line)

 (defun nb/unhide-current-line (limit)
   "Font-lock function"
   (let ((start (max (point) (car nb/current-line)))
         (end (min limit (cdr nb/current-line))))
     (when (< start end)
       (remove-text-properties start end
                       '(invisible t display "" composition ""))
       (goto-char limit)
       t)))

 (defun nb/refontify-on-linemove ()
   "Post-command-hook"
   (let* ((start (line-beginning-position))
          (end (line-beginning-position 2))
          (needs-update (not (equal start (car nb/current-line)))))
     (setq nb/current-line (cons start end))
     (when needs-update
       (font-lock-fontify-block 3))))

 (defun nb/markdown-unhighlight ()
   "Enable markdown concealling"
   (interactive)
   (markdown-toggle-markup-hiding 'toggle)
   (font-lock-add-keywords nil '((nb/unhide-current-line)) t)
   (add-hook 'post-command-hook #'nb/refontify-on-linemove nil t))

;; Toggles on for all MD docs. Remove to turn off.
 (add-hook 'markdown-mode-hook #'nb/markdown-unhighlight)

;; Enable code block syntax highlight
 (setq markdown-enable-highlighting-syntax t)

;; Enable wiki links in all md files by default:
 (setq markdown-enable-wiki-links t)

#+end_src
*** Markdown: Keymaps:
:PROPERTIES:
:ID:       a11d76ba-a718-418a-bead-9531506d9606
:END:
#+begin_src emacs-lisp
; Make emacs auto indent when we create a new list item.
(setq markdown-indent-on-enter 'indent-and-new-item)
#+end_src

** Quality Of Life:
:PROPERTIES:
:ID:       0d1ffcec-769f-4599-8673-d8346a45a735
:END:
*** Save Easier:
:PROPERTIES:
:ID:       225368af-0273-4876-b0db-2906fd3d4f33
:END:
- Stolen from https://github.com/elken/doom
#+begin_src emacs-lisp
;Back to a simpler time…
(map! :g "C-s" #'save-buffer)
#+end_src
*** Search Easier:
:PROPERTIES:
:ID:       edcaf89b-d8fc-4f43-8dc3-206949f7ba23
:END:
- Stolen from https://github.com/elken/doom
#+begin_src emacs-lisp
; Search easily
(map! :after evil :gnvi "C-f" #'consult-line)
#+end_src
*** Use VIM Keybindings to move between windows around:
:PROPERTIES:
:ID:       579b5cb5-5959-44a1-975c-e685fc787649
:END:

- These match my TMUX configs

| COMMAND           | DESCRIPTION           | KEYBINDING |
|-------------------+-----------------------+------------|
| evil-window-Left  | Move One Window Left  | C-h        |
| evil-window-down  | Move One Window Down  | C-j        |
| evil-window-up    | Move One Window Up    | C-k        |
| evil-window-right | Move One Window Right | C-l        |

#+begin_src emacs-lisp
;Use VIM Keybindings to move between windows:
(define-key evil-motion-state-map (kbd "C-h") #'evil-window-left)
(define-key evil-motion-state-map (kbd "C-j") #'evil-window-down)
(define-key evil-motion-state-map (kbd "C-k") #'evil-window-up)
(define-key evil-motion-state-map (kbd "C-l") #'evil-window-right)
#+end_src
*** Zoom In & Out:
:PROPERTIES:
:ID:       fbdea6fb-98d1-446d-87e8-311039e2b1f7
:END:
 - Easily zoom with:
   - In ~C-=~
   - Out ~C--~
#+begin_src emacs-lisp
; Zoom in and Out easily
(defun my/increase-text-height ()
  (interactive)
  (text-scale-increase 1))

(defun my/decrease-text-height ()
  (interactive)
  (text-scale-decrease 1))

(global-set-key (kbd "C-=") 'my/increase-text-height)
(global-set-key (kbd "C--") 'my/decrease-text-height)
#+end_src

*** Enable Emojis
:PROPERTIES:
:ID:       4d49dd8b-efcc-4787-b8a8-d3e6361fdeff
:END:
- Emojify is an Emacs extension to display emojis. It can display github style emojis like :smile: or plain ascii ones like :).

#+begin_src emacs-lisp

;; Enables Emofis
(use-package emojify
  :hook (after-init . global-emojify-mode))

#+end_src

*** INSERT DATE:
:PROPERTIES:
:ID:       5c5411da-e4ce-4c0f-b19e-1a7e301f77c2
:END:
- Taken directly from: https://gitlab.com/dwt1/dotfiles/-/blob/master/.config/doom/config.org?ref_type=heads
  - I have added the insert time parts
Some custom functions to insert the date.  The function 'insert-todays-date' can be used one of three different ways: (1) just the keybinding without the universal argument prefix, (2) with one universal argument prefix, or (3) with two universal argument prefixes.  The universal argument prefix is 'SPC-u' in Doom Emacs (C-u in standard GNU Emacs).  The function 'insert-any-date' only outputs to one format, which is the same format as 'insert-todays-date' without a prefix.

| COMMAND               | EXAMPLE OUTPUT            | KEYBINDING            |
|-----------------------+---------------------------+-----------------------|
| dt/insert-todays-date | /Friday, November 19, 2021/ | SPC i d t             |
| dt/insert-todays-date | /19-11-2021/                | SPC u SPC i d t       |
| dt/insert-todays-date | /2021-11-19/                | SPC u SPC u SPC i d t |
| dt/insert-any-date    | /Friday, November 19, 2021/ | SPC i d a             |

#+begin_src emacs-lisp
(defun dt/insert-todays-date (prefix)
  "Insert today's date based on a prefix."
  (interactive "P")
  (let ((format (cond
                 ((not prefix) "%A, %B %d, %Y")
                 ((equal prefix '(4)) "%d-%m-%Y")
                 ((equal prefix '(16)) "%Y-%m-%d"))))
    (insert (format-time-string format))))

(defun dt/insert-current-time ()
  "Insert the current time in HH:MM:SS format."
  (interactive)
  (insert (format-time-string "%H:%M:%S")))

(require 'calendar)
(defun dt/insert-any-date (date)
  "Insert DATE using the current locale."
  (interactive (list (calendar-read-date)))
  (insert (calendar-date-string date)))

(map! :leader
      (:prefix ("i d" . "Insert date/time")
        :desc "Insert any date"    "a" #'dt/insert-any-date
        :desc "Insert today's date" "t" #'dt/insert-todays-date
        :desc "Insert current time" "c" #'dt/insert-current-time))
#+end_src


* packages.el:
:PROPERTIES:
:ID:       d9847b2d-83c5-44ef-a84b-165b049610f3
:header-args: :tangle ~/Dropbox/40-49_Career/45-KaliShared/45.00-KaliConfigs/Doom/packages.el
:END:

- Dooms package manager. Specify here waht packages to install.
#+begin_src emacs-lisp
(package! emojify)
(package! org-super-agenda)
(package! magithub)
(package! flycheck-aspell)
(package! calfw)
(package! calfw-org)
(package! dashboard)
(package! dired-open)
(package! dired-subtree)
(package! dirvish)
(package! dmenu)
(package! elfeed-goodies)
(package! evil-tutor)
(package! exwm)
(package! ivy-posframe)
(package! mw-thesaurus)
(package! org-auto-tangle)
(package! org-web-tools)
(package! ox-hugo)
;; So I can export org to md well
;;(package! ox-gemini)
(package! peep-dired)
;;(package! password-store)
(package! rainbow-mode)
(package! resize-window)
;;(package! tldr)
(package! wc-mode)
(package! beacon)
;;(package! clippy)
;;(package! minimap)
(package! olivetti)
(package! powershell)
;;(package! multi-vterm)
(package! org-download)
(package! org-ros)
(package! mini-frame)

(package! vlf :recipe (:host github :repo "emacs-straight/vlf" :files ("*.el"))
  :pin "9b7bc521e54af2c7a5c882e4758b66ee4af1a152")
;; For emacs-everywhere browser integration
(package! atomic-chrome)


#+end_src

:header-args: :tangle ~/Dropbox/40-49_Career/45-KaliShared/45.00-KaliConfigs/Doom/init.el
* init.el
:PROPERTIES:
:ID:       f21a8e0a-cc41-45f6-b6e8-8968aa66a9e4
:header-args: :tangle ~/Dropbox/40-49_Career/45-KaliShared/45.00-KaliConfigs/Doom/init.el
:END:
- This file controls what Doom modules are enabled and what order they load in. Remember to run '~doom sync~' after modifying it!
#+begin_src emacs-lisp
;;; init.el -*- lexical-binding: t; -*-

;; This file controls what Doom modules are enabled and what order they load
;; in. Remember to run 'doom sync' after modifying it!


(doom! :input
       ;;chinese
       ;;japanese
       ;;layout            ; auie,ctsrnm is the superior home row

       :completion
       company           ; the ultimate code completion backend
       ;;helm              ; the *other* search engine for love and life
       ;;ido               ; the other *other* search engine...
       ;;ivy               ; a search engine for love and life
       vertico           ; the search engine of the future

       :ui
       deft              ; notational velocity for Emacs
       doom              ; what makes DOOM look the way it does
       doom-dashboard    ; a nifty splash screen for Emacs
       doom-quit         ; DOOM quit-message prompts when you quit Emacs
       (emoji +unicode)  ; 🙂
       hl-todo           ; highlight TODO/FIXME/NOTE/DEPRECATED/HACK/REVIEW
       ;;hydra
       ;;indent-guides     ; highlighted indent columns
       ligatures         ; ligatures and symbols to make your code pretty again
       ;;minimap           ; show a map of the code on the side
       (modeline +ligt)          ; snazzy, Atom-inspired modeline, plus API
       ;;nav-flash         ; blink cursor line after big motions
       neotree           ; a project drawer, like NERDTree for vim
       ophints           ; highlight the region an operation acts on
       (popup +defaults)   ; tame sudden yet inevitable temporary windows
       ;;tabs              ; a tab bar for Emacs
       treemacs          ; a project drawer, like neotree but cooler
       ;;unicode           ; extended unicode support for various languages
       ;;(vc-gutter +pretty)         ; vcs diff in the fringe
       vi-tilde-fringe   ; fringe tildes to mark beyond EOB
       window-select     ; visually switch windows
       workspaces        ; tab emulation, persistence & separate workspaces
       ;;zen               ; distraction-free coding or writing

       :editor
       (evil +everywhere); come to the dark side, we have cookies
       file-templates    ; auto-snippets for empty files
       fold              ; (nigh) universal code folding
       (format +onsave)  ; automated prettiness
       ;;god               ; run Emacs commands without modifier keys
       ;;lispy             ; vim for lisp, for people who don't like vim
       ;;multiple-cursors  ; editing in many places at once
       ;;objed             ; text object editing for the innocent
       ;;parinfer          ; turn lisp into python, sort of
       ;;rotate-text       ; cycle region at point between text candidates
       snippets          ; my elves. They type so I don't have to
       ;;word-wrap         ; soft wrapping with language-aware indent

       :emacs
       (dired +icons)             ; making dired pretty [functional]
       electric          ; smarter, keyword-based electric-indent
       ibuffer         ; interactive buffer management
       undo              ; persistent, smarter undo for your inevitable mistakes
       vc                ; version-control and Emacs, sitting in a tree

       :term
       eshell            ; the elisp shell that works everywhere
       ;;shell             ; simple shell REPL for Emacs
       ;;term              ; basic terminal emulator for Emacs
       vterm             ; the best terminal emulation in Emacs

       :checkers
       syntax              ; tasing you for every semicolon you forget
       ;;(spell +flyspell) ; tasing you for misspelling mispelling
       grammar           ; tasing grammar mistake every you make

       :tools
       ;;ansible
       ;;debugger          ; FIXME stepping through code, to help you add bugs
       ;;direnv
       docker
       ;;editorconfig      ; let someone else argue about tabs vs spaces
       ;;ein               ; tame Jupyter notebooks with emacs
       (eval +overlay)     ; run code, run (also, repls)
       ;;gist              ; interacting with github gists
       lookup              ; navigate your code and its documentation
       lsp               ; M-x vscode
       magit             ; a git porcelain for Emacs
       ;;make              ; run make tasks from Emacs
       ;;pass              ; password manager for nerds
       pdf               ; pdf enhancements
       ;;prodigy           ; FIXME managing external services & code builders
       rgb               ; creating color strings
       taskrunner        ; taskrunner for all your projects
       ;;terraform         ; infrastructure as code
       tmux              ; an API for interacting with tmux
       ;;upload            ; map local to remote projects via ssh/ftp

       :os
       ;;(:if IS-MAC macos)  ; improve compatibility with macOS
       tty               ; improve the terminal Emacs experience

       :lang
       ;;agda              ; types of types of types of types...
       ;;beancount         ; mind the GAAP
       ;;cc                ; C > C++ == 1
       ;;clojure           ; java with a lisp
       ;;common-lisp       ; if you've seen one lisp, you've seen them all
       ;;coq               ; proofs-as-programs
       ;;crystal           ; ruby at the speed of c
       ;;csharp            ; unity, .NET, and mono shenanigans
       data              ; config/data formats
       ;;(dart +flutter)   ; paint ui and not much else
       ;;dhall
       ;;elixir            ; erlang done right
       ;;elm               ; care for a cup of TEA?
       emacs-lisp        ; drown in parentheses
       ;;erlang            ; an elegant language for a more civilized age
       ;;ess               ; emacs speaks statistics
       ;;factor
       ;;faust             ; dsp, but you get to keep your soul
       ;;fsharp            ; ML stands for Microsoft's Language
       ;;fstar             ; (dependent) types and (monadic) effects and Z3
       ;;gdscript          ; the language you waited for
       ;;(go +lsp)         ; the hipster dialect
       ;;(haskell +lsp)    ; a language that's lazier than I am
       ;;hy                ; readability of scheme w/ speed of python
       ;;idris             ; a language you can depend on
       json              ; At least it ain't XML
       ;;(java +meghanada) ; the poster child for carpal tunnel syndrome
       javascript        ; all(hope(abandon(ye(who(enter(here))))))
       ;;julia             ; a better, faster MATLAB
       ;;kotlin            ; a better, slicker Java(Script)
       ;;latex             ; writing papers in Emacs has never been so fun
       ;;lean              ; for folks with too much to prove
       ;;ledger            ; be audit you can be accounting
       ;;lua               ; one-based indices? one-based indices
       (markdown +grip)          ; writing docs for people to ignore
       ;;nim               ; python + lisp at the speed of c
       nix               ; I hereby declare "nix geht mehr!"
       ;;ocaml             ; an objective camel
       (org +pretty
            +journal
            +hugo
            +pandoc
            +present
            +dragndrop
            +pomodoro
            +habit)               ; organize your plain life in plain text)
       php               ; perl's insecure younger brother
       ;;plantuml          ; diagrams for confusing people more
       ;;purescript        ; javascript, but functional
       python            ; beautiful is better than ugly
       powershell         ; will it work?
       ;;qt                ; the 'cutest' gui framework ever
       ;;racket            ; a DSL for DSLs
       ;;raku              ; the artist formerly known as perl6
       ;;rest              ; Emacs as a REST client
       ;;rst               ; ReST in peace
       ;;(ruby +rails)     ; 1.step {|i| p "Ruby is #{i.even? ? 'love' : 'life'}"}
       ;;rust              ; Fe2O3.unwrap().unwrap().unwrap().unwrap()
       ;;scala             ; java, but good
       ;;(scheme +guile)   ; a fully conniving family of lisps
       sh                ; she sells {ba,z,fi}sh shells on the C xor
       ;;sml
       ;;solidity          ; do you need a blockchain? No.
       ;;swift             ; who asked for emoji variables?
       ;;terra             ; Earth and Moon in alignment for performance.
       web               ; the tubes
       yaml              ; JSON, but readable
       ;;zig               ; C, but simpler

       :email
       ;;(mu4e +org +gmail)
       ;;notmuch
       ;;(wanderlust +gmail)

       :app
       ;;calendar
       ;;emms
       everywhere        ; *leave* Emacs!? You must be joking
       ;;irc               ; how neckbeards socialize
       ;;(rss +org)        ; emacs as an RSS reader
       ;;twitter           ; twitter client https://twitter.com/vnought

       :config
       ;;literate
       (default +bindings +smartparens))
#+end_src
