---
- name: Configure Kali Linux
  hosts: all
  become: yes  # This is equivalent to using sudo
  vars:
    user_home: "/home/vagrant"
    docker_gpg_key_url: "https://download.docker.com/linux/debian/gpg"
    docker_repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian bookworm stable"

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Download Iosevka Nerd Font (be patient big file!)
      get_url:
        url: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.3.0/Iosevka.zip
        dest: /tmp/Iosevka.zip
        mode: '0644'

    - name: Install unzip if not present
      apt:
        name: unzip
        state: present

    - name: Extract Iosevka font
      unarchive:
        src: /tmp/Iosevka.zip
        dest: "/usr/local/share/fonts/"
        remote_src: yes
        owner: vagrant
        group: vagrant

    - name: Update font cache
      command: fc-cache -fv
      become_user: vagrant

    - name: Install base packages
      apt:
        name:
          - eza
          - alacritty
          - git
          - bat
          - seclists
          - git 
          - emacs
          - ripgrep
          - fd-find
        state: present

    - name: Create docker GPG directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Check if Docker GPG key exists
      stat:
        path: /etc/apt/keyrings/docker.gpg
      register: docker_gpg

    - name: Add Docker GPG key
      shell: |
        curl -fsSL {{ docker_gpg_key_url }} | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
      when: not docker_gpg.stat.exists

    - name: Check if Docker repository exists
      stat:
        path: /etc/apt/sources.list.d/docker.list
      register: docker_repo_file

    - name: Add Docker repository
      copy:
        content: "{{ docker_repo }}"
        dest: /etc/apt/sources.list.d/docker.list
      when: not docker_repo_file.stat.exists

    - name: Install Docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        update_cache: yes
        state: present

    - name: Download Starship install script
      get_url:
        url: https://starship.rs/install.sh
        dest: /tmp/starship-install.sh
        mode: '0755'
      register: download_script

    - name: Install Starship
      shell: /tmp/starship-install.sh --yes
      args:
        creates: /usr/local/bin/starship
      when: download_script is success
      async: 180  # 5 minute timeout
      poll: 5     # Check every 5 seconds

    - name: Install oh-my-zsh
      become_user: vagrant
      shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
      args:
        creates: "{{ user_home }}/.oh-my-zsh"

    - name: Install zsh plugins
      become_user: vagrant
      git:
        repo: "{{ item.repo }}"
        dest: "{{ user_home }}/.oh-my-zsh/custom/plugins/{{ item.name }}"
      loop:
        - { repo: 'https://github.com/zsh-users/zsh-autosuggestions', name: 'zsh-autosuggestions' }
        - { repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git', name: 'zsh-syntax-highlighting' }
        - { repo: 'https://github.com/marlonrichert/zsh-autocomplete.git', name: 'zsh-autocomplete' }
        - { repo: 'https://github.com/zdharma-continuum/fast-syntax-highlighting.git', name: 'fast-syntax-highlighting' }

    - name: Install tmuxinator
      gem:
        name: tmuxinator
        state: present

    - name: Clone Statistically Likely Usernames
      git:
        repo: https://github.com/insidetrust/statistically-likely-usernames.git
        dest: /usr/share/wordlists/statistically-likely-usernames

    - name: Download and install Kerbrute
      get_url:
        url: https://github.com/ropnop/kerbrute/releases/download/v1.0.3/kerbrute_linux_amd64
        dest: /usr/local/bin/kerbrute
        mode: '0755'

    - name: Install build dependencies for Emacs
      apt:
        name:
          - build-essential
          - libgccjit-12-dev
          - libgnutls28-dev
          - libjansson4
          - libjansson-dev
          - libncurses-dev
          - libsqlite3-dev
          - libgif-dev
          - libjpeg-dev
          - libpng-dev
          - libtiff5-dev
          - libxpm-dev
          - libwebp-dev
          - libgtk-3-dev
          - texinfo
          - autoconf
          - automake
          - pkg-config
        state: present
        install_recommends: no
      register: pkg_result
      retries: 3
      delay: 5
      until: pkg_result is success

    - name: Install tree-sitter separately
      apt:
        name: libtree-sitter-dev
        state: present
      register: tree_sitter_result
      retries: 3
      delay: 5
      until: tree_sitter_result is success

    - name: Check if Emacs 29.4 is installed
      command: emacs --version
      register: emacs_version
      ignore_errors: true
      changed_when: false

    - name: Clone Emacs repository
      git:
        repo: git://git.savannah.gnu.org/emacs.git
        dest: /tmp/emacs
        version: emacs-29.4
      when: "emacs_version.rc != 0 or '29.4' not in emacs_version.stdout|default('')"

    - name: Run autogen
      shell: |
        cd /tmp/emacs
        ./autogen.sh
      when: "emacs_version.rc != 0 or '29.4' not in emacs_version.stdout|default('')"

    - name: Configure Emacs
      shell: |
        cd /tmp/emacs
        ./configure --with-native-compilation --with-json --with-tree-sitter --with-sqlite3
      args:
        creates: /tmp/emacs/Makefile
      when: "emacs_version.rc != 0 or '29.4' not in emacs_version.stdout|default('')"

    - name: Build Emacs
      shell: |
        cd /tmp/emacs
        make -j$(nproc)
      args:
        creates: /tmp/emacs/src/emacs
      when: "emacs_version.rc != 0 or '29.4' not in emacs_version.stdout|default('')"
      async: 1800
      poll: 15

    - name: Install Emacs
      become: yes
      shell: |
        cd /tmp/emacs
        make install
      args:
        creates: /usr/local/bin/emacs
      when: "emacs_version.rc != 0 or '29.4' not in emacs_version.stdout|default('')"
      async: 900
      poll: 15

    - name: Install other base packages
      apt:
        name:
          - eza
          - alacritty
          - git
          - bat
          - seclists
          - ripgrep
          - fd-find
        state: present
        install_recommends: no

    - name: Setup dotfiles
      become_user: vagrant
      block:
        - name: Clone dotfiles
          git:
            repo: https://github.com/bloodstiller/kaliconfigs.git
            dest: "{{ user_home }}/.dotfiles"
            version: main  # Or whatever branch you're using
            update: yes # Ensures latest version is cloned
            clone: yes
            force: yes  # This will overwrite local changes
        - name: Create required directories
          file:
            path: "{{ item }}"
            state: directory
          loop:
            - "{{ user_home }}/.doom.d"
            - "{{ user_home }}/.config"

        - name: Create symlinks
          file:
            src: "{{ item.src }}"
            dest: "{{ item.dest }}"
            state: link
            force: yes
          loop:
            - { src: "{{ user_home }}/.dotfiles/Zsh/.zshrc", dest: "{{ user_home }}/.zshrc" }
            - { src: "{{ user_home }}/.dotfiles/Doom/config.el", dest: "{{ user_home }}/.doom.d/config.el" }
            - { src: "{{ user_home }}/.dotfiles/Doom/init.el", dest: "{{ user_home }}/.doom.d/init.el" }
            - { src: "{{ user_home }}/.dotfiles/Doom/packages.el", dest: "{{ user_home }}/.doom.d/packages.el" }
            - { src: "{{ user_home }}/.dotfiles/Doom/README.org", dest: "{{ user_home }}/.doom.d/README.org" }
            - { src: "{{ user_home }}/.dotfiles/Starship/starship.toml", dest: "{{ user_home }}/.config/starship.toml" }
            - { src: "{{ user_home }}/.dotfiles/Alacritty", dest: "{{ user_home }}/.config/Alacritty" }
            - { src: "{{ user_home }}/.dotfiles/Tmux/.tmux.conf", dest: "{{ user_home }}/.tmux.conf" }

    - name: Install Doom Emacs
      become_user: vagrant
      block:
        - name: Clone Doom Emacs
          git:
            repo: https://github.com/doomemacs/doomemacs
            dest: "{{ user_home }}/.config/emacs"
            depth: 1

        - name: Install Doom Emacs
          # This is correct and the path is correct!
          shell: "{{ user_home }}/.config/emacs/bin/doom install --force"
          args:
            creates: "{{ user_home }}/.emacs.d/bin/doom"
          async: 900
          poll: 15

        - name: Update Doom recipe repositories
          shell: "{{ user_home }}/.config/emacs/bin/doom sync -u"
          async: 900
          poll: 15


    - name: Enable Docker service
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Add user to docker group
      user:
        name: vagrant
        groups: docker
        append: yes

    - name: Clean up
      apt:
        autoremove: yes
        clean: yes

